-- Kelime modu: TEK BİRLEŞİK havuz (gizli belirleme + tahmin aynı havuzdan).
--
-- KARAR: valid_words (tahmin havuzu, 16.469) içindeki kelimeler çoğunlukla
-- bilindik/kullanılan değil (arkaik, özel isim, çöp: vlbk/lgbt). Tek havuzdan
-- gidilir: secret_words (yaygın, aile-dostu, frekans sıralı) HEM gizli belirleme
-- HEM tahmin için kullanılır; valid_words KALDIRILIR.
--
-- 4-6 harfli "bilinen" Türkçe kelime tavanı ~5.000 (OpenSubtitles frekans verisi).
-- Bu migration secret_words'e 275 yaygın kelime ekler (küfür + özel isim filtreli;
-- bkz. scripts/gen-word-pool.mjs) → ~4.975 kelimelik tek havuz.
--
-- SIRA: önce is_valid_guess_for'u secret_words'e yönelt, SONRA valid_words'ü drop
-- et (fonksiyon kırılmasın). is_valid_secret_for zaten secret_words'e bakıyordu.

-- ─── 1) Tek havuza yeni yaygın kelimeler (frekans sıralı; on conflict = idempotent) ───
insert into public.secret_words (word) values
  ('için'),
  ('evet'),
  ('değil'),
  ('hayır'),
  ('daha'),
  ('kadar'),
  ('bana'),
  ('gibi'),
  ('bunu'),
  ('tamam'),
  ('sana'),
  ('neden'),
  ('zaman'),
  ('sadece'),
  ('burada'),
  ('nasıl'),
  ('sonra'),
  ('şimdi'),
  ('öyle'),
  ('önce'),
  ('biraz'),
  ('hadi'),
  ('yani'),
  ('böyle'),
  ('lütfen'),
  ('onun'),
  ('bile'),
  ('çünkü'),
  ('peki'),
  ('eğer'),
  ('artık'),
  ('geri'),
  ('olarak'),
  ('başka'),
  ('belki'),
  ('doğru'),
  ('olan'),
  ('biri'),
  ('hiçbir'),
  ('demek'),
  ('nerede'),
  ('işte'),
  ('bütün'),
  ('diye'),
  ('tabii'),
  ('bize'),
  ('selam'),
  ('göre'),
  ('yoksa'),
  ('hala'),
  ('yine'),
  ('zaten'),
  ('onlar'),
  ('birkaç'),
  ('şunu'),
  ('nereye'),
  ('lanet'),
  ('karşı'),
  ('fakat'),
  ('bunlar'),
  ('niye'),
  ('falan'),
  ('onlara'),
  ('senden'),
  ('bazı'),
  ('ayrıca'),
  ('beri'),
  ('sence'),
  ('hangi'),
  ('ancak'),
  ('tabi'),
  ('ciddi'),
  ('hatta'),
  ('sende'),
  ('silah'),
  ('evlat'),
  ('kere'),
  ('neyi'),
  ('şöyle'),
  ('üzere'),
  ('yemin'),
  ('birçok'),
  ('neye'),
  ('adına'),
  ('rağmen'),
  ('defa'),
  ('dolayı'),
  ('aşık'),
  ('mesela'),
  ('niçin'),
  ('sizden'),
  ('kimi'),
  ('hani'),
  ('dahil'),
  ('plan'),
  ('günde'),
  ('madem'),
  ('ilaç'),
  ('sizce'),
  ('filan'),
  ('bizde'),
  ('vahşi'),
  ('dahi'),
  ('aniden'),
  ('zorla'),
  ('bari'),
  ('tıbbi'),
  ('hakim'),
  ('sizde'),
  ('taze'),
  ('korkma'),
  ('ilan'),
  ('bela'),
  ('fare'),
  ('kanun'),
  ('alarm'),
  ('klasik'),
  ('jüri'),
  ('tarif'),
  ('ötürü'),
  ('telafi'),
  ('amin'),
  ('sabaha'),
  ('reklam'),
  ('hali'),
  ('oysa'),
  ('bozucu'),
  ('üzülme'),
  ('imza'),
  ('adet'),
  ('samimi'),
  ('kapıda'),
  ('bekar'),
  ('sent'),
  ('eğil'),
  ('lakin'),
  ('kuşlar'),
  ('kuralı'),
  ('mali'),
  ('lastik'),
  ('layık'),
  ('güce'),
  ('siyasi'),
  ('feci'),
  ('isabet'),
  ('şahsi'),
  ('nakil'),
  ('hint'),
  ('iflas'),
  ('havai'),
  ('ahlaki'),
  ('malum'),
  ('ahlak'),
  ('siyahi'),
  ('ticari'),
  ('amir'),
  ('maddi'),
  ('harbi'),
  ('ilahi'),
  ('manuel'),
  ('yabani'),
  ('ukala'),
  ('monte'),
  ('göle'),
  ('tekila'),
  ('seneye'),
  ('nihai'),
  ('istila'),
  ('medeni'),
  ('dileme'),
  ('mani'),
  ('lamba'),
  ('ayin'),
  ('kabile'),
  ('iskoç'),
  ('aciz'),
  ('züppe'),
  ('hakiki'),
  ('çoklu'),
  ('plaka'),
  ('flaş'),
  ('şunlar'),
  ('illa'),
  ('lahana'),
  ('jambon'),
  ('şahıs'),
  ('mağlup'),
  ('kadim'),
  ('pilav'),
  ('onunki'),
  ('karlı'),
  ('arılar'),
  ('klas'),
  ('helal'),
  ('villa'),
  ('plaj'),
  ('alarma'),
  ('hukuki'),
  ('telaş'),
  ('joker'),
  ('tabela'),
  ('akli'),
  ('elmalı'),
  ('rahim'),
  ('değin'),
  ('klon'),
  ('suni'),
  ('rakun'),
  ('kısmi'),
  ('lavabo'),
  ('ödemiş'),
  ('ibadet'),
  ('itibar'),
  ('alaka'),
  ('kıta'),
  ('jaguar'),
  ('varis'),
  ('alem'),
  ('pili'),
  ('irade'),
  ('mecazi'),
  ('vakıf'),
  ('asabi'),
  ('alamet'),
  ('salsa'),
  ('sake'),
  ('idari'),
  ('lama'),
  ('şifa'),
  ('tabir'),
  ('zümrüt'),
  ('üzme'),
  ('ulaş'),
  ('rika'),
  ('kimisi'),
  ('umumi'),
  ('mimari'),
  ('jakuzi'),
  ('fani'),
  ('platin'),
  ('hadise'),
  ('adalar'),
  ('mahsus'),
  ('zürafa'),
  ('vesile'),
  ('şelale'),
  ('portal'),
  ('plato'),
  ('ceylan'),
  ('polen'),
  ('nazir'),
  ('hilal'),
  ('fahri'),
  ('sari'),
  ('sulama'),
  ('jöleli'),
  ('zile'),
  ('klavye'),
  ('idol'),
  ('alim'),
  ('ağın'),
  ('farazi'),
  ('lale'),
  ('kulu'),
  ('beli'),
  ('latif'),
  ('zara'),
  ('varma'),
  ('imam'),
  ('etobur'),
  ('kasti'),
  ('leylak'),
  ('larva'),
  ('uçun'),
  ('obez')
on conflict (word) do nothing;

-- ─── 2) Tahmin doğrulamasını TEK havuza (secret_words) yönelt ───────────
-- Gövde 20260611000001'den; tek fark: word dalı valid_words → secret_words.
create or replace function public.is_valid_guess_for(p_content_type text, p_value text, p_length int default null)
returns boolean
language plpgsql stable
as $$
begin
  if p_content_type = 'number' then
    return public.is_valid_secret(p_value);
  elsif p_content_type = 'word' then
    return (p_length is null or char_length(p_value) = p_length)
       and exists (select 1 from public.secret_words where word = p_value);
  end if;
  raise exception 'unknown_content_type';
end;
$$;

-- ─── 3) Eski tahmin havuzunu KALDIR (RLS/grant/index cascade) ───────────
drop table if exists public.valid_words cascade;

notify pgrst, 'reload schema';
